// Copyright (C) 2026 by Vladyslav V. Prodan <github.com/click0>. All rights reserved.

#include "inter_dns_pure.h"

#include <algorithm>
#include <sstream>

namespace InterDnsPure {

static const char *BLOCK_BEGIN = "# >>> crate inter-container DNS <<<";
static const char *BLOCK_END   = "# <<< crate inter-container DNS >>>";

std::string validateHostname(const std::string &name) {
  if (name.empty()) return "hostname is empty";
  if (name.size() > 63) return "hostname is longer than 63 chars";
  auto isAlnum = [](char c) {
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
        || (c >= '0' && c <= '9');
  };
  if (!isAlnum(name.front())) return "hostname must start with a letter or digit";
  if (!isAlnum(name.back()))  return "hostname must end with a letter or digit";
  for (auto c : name) {
    if (!isAlnum(c) && c != '-') {
      std::ostringstream os;
      os << "invalid character '" << c << "' in hostname";
      return os.str();
    }
  }
  return "";
}

std::string normalizeName(const std::string &name) {
  std::string out;
  out.reserve(name.size());
  for (auto c : name) {
    if (c >= 'A' && c <= 'Z') c = c - 'A' + 'a';
    out += c;
  }
  return out;
}

namespace {

std::vector<Entry> sortedByName(const std::vector<Entry> &in) {
  std::vector<Entry> out = in;
  std::sort(out.begin(), out.end(), [](const Entry &a, const Entry &b) {
    return normalizeName(a.name) < normalizeName(b.name);
  });
  return out;
}

} // anon

std::string buildUnboundFragment(const std::vector<Entry> &entries) {
  auto sorted = sortedByName(entries);
  std::ostringstream os;
  os << "# Auto-generated by crate(8) — do not edit by hand.\n"
     << "# Re-run `crate inter-dns rebuild` after starting/stopping containers.\n"
     << "server:\n"
     << "  local-zone: \"crate.\" static\n";
  for (auto &e : sorted) {
    auto n = normalizeName(e.name);
    if (!e.ip4.empty())
      os << "  local-data: \"" << n << ".crate. IN A "    << e.ip4 << "\"\n";
    if (!e.ip6.empty())
      os << "  local-data: \"" << n << ".crate. IN AAAA " << e.ip6 << "\"\n";
  }
  return os.str();
}

std::string buildHostsBlock(const std::vector<Entry> &entries) {
  auto sorted = sortedByName(entries);
  std::ostringstream os;
  os << BLOCK_BEGIN << "\n";
  for (auto &e : sorted) {
    auto n = normalizeName(e.name);
    if (!e.ip4.empty()) {
      os << e.ip4 << "\t" << n << ".crate " << n << "\n";
    } else if (!e.ip6.empty()) {
      os << e.ip6 << "\t" << n << ".crate " << n << "\n";
    }
  }
  os << BLOCK_END << "\n";
  return os.str();
}

std::string replaceHostsBlock(const std::string &existing,
                              const std::string &block) {
  auto begin = existing.find(BLOCK_BEGIN);
  if (begin == std::string::npos) {
    // No prior block — append, ensuring a trailing newline.
    std::string out = existing;
    if (!out.empty() && out.back() != '\n') out += '\n';
    out += block;
    return out;
  }
  auto end = existing.find(BLOCK_END, begin);
  if (end == std::string::npos) {
    // Malformed: drop everything from the begin-marker forward and
    // append the new block. This recovers from a half-written block.
    std::string out = existing.substr(0, begin);
    if (!out.empty() && out.back() != '\n') out += '\n';
    out += block;
    return out;
  }
  // Skip past the BLOCK_END line itself plus its newline.
  end += std::string(BLOCK_END).size();
  if (end < existing.size() && existing[end] == '\n') end++;
  std::string out = existing.substr(0, begin) + block + existing.substr(end);
  return out;
}

} // namespace InterDnsPure
